FROM node:16-alpine

WORKDIR /app

COPY ./package.json /app/

RUN npm install 

#There is no need for this actually because we are  using volumes when running container which
#looks for the change in the code locally
COPY ./ /app/

CMD ["npm", "run", "start"]